import { Colors } from "../../common/Colors";

export const styles = {
  container: {
    flex: 1,
    backgroundColor: Colors.middleColor,
  },
  linearGradient: {
    flex: 1,
  },
  title: {
    fontSize: 24,
    lineHeight: 37.33,
    textAlign: "left",
    color: Colors.white,
    fontFamily: "SairaCondensed-Medium",
  },
  listingTextView: {
    paddingHorizontal: 15,
    marginBottom: 7,
  },
  listingTitle: {
    fontSize: 24,
    lineHeight: 37.33,
    // textAlign: "left",
    color: Colors.white,
    fontFamily: "SairaCondensed-Medium",
  },
  tag: {
    height: 28,
    margin: 8,
    borderWidth: 1.5,
    borderRadius: 12,
    alignItems: "center",
    paddingHorizontal: 10,
    justifyContent: "center",
    borderColor: Colors.button,
  },
  seeMore: {
    fontSize: 12,
    lineHeight: 18,
    color: Colors.switchColor,
    fontFamily: "SairaCondensed-Medium",
  },
  accountText: {
    fontSize: 14,
    lineHeight: 22,
    color: Colors.white,
    fontFamily: "SairaCondensed-Medium",
  },
  subAccountText: {
    fontSize: 14,
    lineHeight: 22,
    color:Colors.switchColor,
    fontFamily: "SairaCondensed-Medium",
  },
  bottomView: {
    paddingTop: 25,
    flexDirection: "row",
    justifyContent: "center",
  },

  message: {
    width: 20,
    height: 15,
    marginEnd: 8,
  },
  icon: {
    width: 17,
    height: 20,
    marginEnd: 8,
  },
  email: {
    fontSize: 14,
    lineHeight: 22,
    marginBottom: 8,
    textAlign: "left",
    color: Colors.white,
    fontFamily: "SairaCondensed-Medium",
  },
  inputView: {
    marginTop: 8,
    marginBottom: 20,
    paddingHorizontal: 15,
  },
  orText: {
    fontSize: 14,
    lineHeight: 17,
    marginBottom: 8,
    textAlign: "center",
    color: Colors.white,
    fontFamily: "SairaCondensed-Medium",
  },
  socialContainer: {
    flexDirection: "row",
    paddingHorizontal: 10,
    justifyContent: "space-evenly",
  },
  google: {
    height: 18,
    width: 18.2,
  },
  twitter: {
    width: 21,
    height: 18,
  },
  facebook: {
    height: 21,
    width: 12,
  },
  cardTitle: {
    fontSize: 25,
    lineHeight: 39.33,
    textAlign: "left",
    color: Colors.white,
    fontFamily: "SairaCondensed-Medium",
  },
  description: {
    fontSize: 12,
    lineHeight: 18,
    textAlign: "left",
    color: Colors.white,
    fontFamily: "SairaCondensed-Light",
  },
  cardSubTitle: {
    fontSize: 15,
    lineHeight: 23,
    textAlign: "left",
    color: Colors.white,
    fontFamily: "SairaCondensed-Medium",
  },
  dateText: {
    fontSize: 15,
    lineHeight: 23,
    color: Colors.switchColor,
    fontFamily: "SairaCondensed-Light",
  },
  dateCard: {
    padding: 15,
    marginTop: 10,
    borderRadius: 20,
    flexDirection: "row",
    backgroundColor: Colors.input,
    justifyContent: "space-between",
  },
  deliveryCard: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  card: {
    backgroundColor: Colors.input,
    borderRadius: 20,
    marginTop: 10,
    padding: 20,
  },
  available: {
    fontSize: 15,
    lineHeight: 23,
    marginVertical: 5,
    color: Colors.white,
    fontFamily: "SairaCondensed-Light",
  },
  headSticker: {
    backgroundColor: Colors.button,
    borderColor: Colors.switchColor,
    justifyContent: "center",
    paddingHorizontal: 7,
    alignItems: "center",
    paddingVertical: 5,
    borderWidth: 0.5,
    borderRadius: 6,
    // width: 73,
    margin: 3,
  },
  stickerText: {
    fontSize: 10,
    lineHeight: 15,
    color: Colors.switchColor,
  },
  btnContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 15,
  },
  btn: {
    flex: 0.45,
    backgroundColor: Colors.button,
    justifyContent: "space-evenly",
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 9,
    borderRadius: 20,
  },
  btnText: {
    marginTop: 3,
    fontSize: 20,
    lineHeight: 25,
    marginRight: 10,
    color: Colors.white,
    fontFamily: "SairaCondensed-Medium",
  },
  scrollView: {
    paddingHorizontal: 20,
    marginBottom: 10,
  },
  cardImage: {
    backgroundColor: Colors.input,
    borderRadius: 20,
  },
  editText:{
    fontSize: 18,
    lineHeight: 28,
    marginRight: 10,
    color: Colors.switchColor,
    fontFamily: "SairaCondensed-Bold",
  },
  img: {
    height: 350,
    width: "100%",
    borderRadius: 20,
  },
  threeImages: {
    left: 0,
    right: 0,
    bottom: 150,
    position: "absolute",
    flexDirection: "row",
    paddingHorizontal: 20,
    justifyContent: "space-between",
  },
  positionImage: {
    borderRadius: 20,
    height: 152,
    width: 120,
  },
  twoImages: {
    left: 10,
    right: 10,
    bottom: 100,
    alignItems: "center",
    position: "absolute",
  },
  oneImage: {
    borderRadius: 20,
    height: 152,
    width: 280,
  },
  carousel: {
    height: 260,
    paddingTop: 30,
    justifyContent: "center",
  },
  carouselCard: {
    paddingHorizontal: 15,
    alignItems: "center",
    paddingTop: 20,
  },
  carouselImage: {
    width: 130,
    height: 160,
    borderRadius: 15,
  },
  mainContainer: {
    justifyContent: "space-between",
    alignItems: "center",
    flexDirection: "row",
    padding: 15,
  },
  btnIcon: {
    height: 20,
    width: 25,
  },
};
